# Generated by Django 5.0.4 on 2024-05-06 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending')),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField(editable=False)),
                ('acknowledgment_date', models.DateTimeField(editable=False, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendors')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
