# Generated by Django 5.0.4 on 2024-05-06 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
        ('vendor', '0002_vendorsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorsmodel'),
        ),
    ]
